apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pui9cfnhd-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pui9cfnhd-python 
  name: pui9cfnhd-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pui9cfnhd-python 
