apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pui9cfnhd-python 
  janus-idp.io/tekton: pui9cfnhd-python
  backstage.io/kubernetes-id: pui9cfnhd-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pui9cfnhd-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  